name: Unit Testing
on:
  pull_request:
    branches: [ test ]
  push:
    branches: [ test ]

jobs:
  unit_testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          pip install pandas

          # Install any dependencies needed for unit tests

      - name: Run Unit Tests
        run: |
          # Command to run unit tests
          # Example: python -m unittest discover -s tests -p '*_test.py'
          pytest test.py
